export enum Tags {
    BUILDING = 'building',
    SPACE = 'space',
    SCIENCE = 'science',
    ENERGY = 'power',
    EARTH = 'Earth',
    JOVIAN = 'Jovian',
    VENUS = 'Venus',
    PLANT = 'plant',
    MICROBE = 'microbe',
    ANIMAL = 'animal',
    CITY = 'city',
    MOON = 'Moon',
    MARS = 'Mars',
    WILDCARD = 'wild',
    EVENT = 'event',
    CLONE = 'clone',
}
